### ISSUE TITLE
CICD & Linter/Formatter

### ISSUE THREAD

**Issue by verySmolBrain** [trentzz/checkers-board-tournament#11]
![a](https://github.com/user-attachments/assets/312d2070-1df7-4861-80e9-63dc642bb78b)

**Comment by trentzz** [comment]
fixed in latest pr :(

**Comment by trentzz** [comment]
yessir

**Comment by trentzz** [comment]
I merged the PR into `issues/11-cicd-linterformatter` and I'll tinker with that formatting a little bit before merging into `add-your-bot-here`
