### ISSUE TITLE
Chain captures

### ISSUE THREAD

**Issue by donren-leung** [trentzz/checkers-board-tournament#23]
In the rules of checkers, if you can keep capturing, you must. Currently captures stop at one, so let's implement the correct behaviour.

For simplicity, a whole capturing sequence should be represented as one `Move`, that way move selection is unchanged for bots. This requires changing `Move.removed` from a single optional tuple, to a list of position tuples.

**Comment by trentzz** [comment]
Hmm I think it might be important to keep track of all the positions in between the chain capture moves, instead of just the start and final position of the piece and all the captured positions. 

I propose having a ListMove which a list of Move. This way we can keep a lot of our existing logic for handling and updating board logic. 

You could technically figure out what the in between positions by searching for valid moves are but I think thats very unnecessary.

**Comment by donren-leung** [comment]
For updating the board, you only need to move the moving piece from start to end coordinate, which we already have, and remove all captured pieces, which would be tracked with the list of tuples.

As long as the captures are kept in order, you can easily recover the intermediate positions of the moving piece (it's twice the vector from its previous spot). You may want these stepping squares when displaying the board to follow it easier.

**Comment by trentzz** [comment]
Thoughts on having a list of inbetween positions in Move?

So move has:
start: Tuple
end: Tuple
inbetween: list[tuple]
removed: list[tuple]

**Comment by trentzz** [comment]
I guess it also comes down to what do you consider a move? Is a chain of captures a single move, or is each of those captures an individual move?

And just a thought, are there scenarios where you have a lot of potential variations of chain capture moves available such that the move_list becomes giant?

Oh and if a chain of captures is a single move, the get_move_list would have to recursively search.

**Comment by donren-leung** [comment]
For me it's the choice you make, after which it's your opponent choice. As such they are atomic - making you choose a move after you've already made one does not make sense.

Not really, at least for man pieces the most you can do is a triple capture since you always have to move up the board. Even for kings you have to keep capturing until you can't - I imagine a lot of capturing submoves are forced.

Recursive search to find these is fine

**Comment by trentzz** [comment]
Sure that makes sense to me, we should probs write that somewhere in docs just to be explicit.

Thoughts on the inbetween position list?

**Comment by donren-leung** [comment]
That can be a method, I don't see it necessary to be generated for every Move.

**Comment by trentzz** [comment]
It gets generated for every move anyways because it has to right, when you're making the move_list and recursively searching for available moves. 

The cost here is storing stuff we might not need, e.g. not needed if: bots don't care, we're not printing the board, we're not exporting pdn.

**Comment by donren-leung** [comment]
Yup that's what I meant, `Move` object needs to be as bare bones as possible, since that is key for all engines' move generation for new positions.
Does #28 look good?
