### ISSUE TITLE
Draw by repetition/duplicate board positions

### ISSUE THREAD

**Issue by donren-leung** [trentzz/checkers-board-tournament#26]
Title.

Hash away the board grid

**Comment by trentzz** [comment]
Ooh you could just have a deque of length 3/6 whatever the repeated move condition is, and pop_front, push_back to maintain the list.

**Comment by donren-leung** [comment]
Duplicate positions are not necessarily back to back to back, e.g. you could have kings going in circles. A hashmap of Boards would allow you to check against the entire game history.

**Comment by trentzz** [comment]
Oh wait so a draw can happen if the same board position is reached 3 times at any point in the game?

**Comment by donren-leung** [comment]
Yes https://en.wikipedia.org/wiki/Threefold_repetition
